version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_sta 
    environment:
      MYSQL_ROOT_PASSWORD: sta-pass
      MYSQL_DATABASE: sta.db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_sta:/var/lib/mysql
    networks:
      - mi_red

  phpmyadmin:
    image: phpmyadmin/phpmyadmin         
    container_name: phpmyadmin_sta
    environment:
      PMA_HOST: mysql_db_sta 
      MYSQL_ROOT_PASSWORD: sta-pass 
    ports:
      - "8080:80"                        
    depends_on:
      - mysql                             
    networks:
      - mi_red

  php:
    build: .
    image: php:8.0-fpm 
    container_name: php_fpm
    volumes:
      - ./web:/usr/share/nginx/html 
    networks:
      - mi_red

  nginx:
    image: nginx:latest  
    container_name: my_nginx
    volumes:
      - ./web:/usr/share/nginx/html  # Comparte el volumen ./web con Nginx
      - ./nginx.conf:/etc/nginx/nginx.conf  # Añadimos la configuración para PHP
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - mi_red    

volumes:
  mysql_data_sta:

networks:
  mi_red:
    driver: bridge